#PORTA SERVIDOR LOCAL
server:
  port: 8081
#CONFIGURAÇÃO DE ACESSO AO BANCO DE DADOS
spring:
  datasource:
    url: jdbc:h2:mem:api_publica
    username: root
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    show_sql: true
    format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
#CONFIGURAÇÕES DE LOG
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: INFO